### ISSUE TITLE
fix addon request

### ISSUE THREAD

**Issue by xZeroW** [weizlogy/tos#11]
Hi, first of all, I'd like to thank you for your addons.
I would like to ask if it's possible to you to fix the itemdrops addonmade by imei.

**Comment by weizlogy** [comment]
I can do that, if functions is not prevented by programmatically.

**Comment by weizlogy** [comment]
where is the itemdrops addon's source?

**Comment by xZeroW** [comment]
itemdrops.lua [https://pastebin.com/0SgmQ8Nk](https://pastebin.com/0SgmQ8Nk)
itemdrops.xml
 ```
<?xml version="1.0" encoding="UTF-8"?>
<uiframe name="itemdrops" x="0" y="0" width="32" height="32" create="open" />
```
thanks

**Comment by weizlogy** [comment]
hi, i fixed it.

https://github.com/weizlogy/tos/releases/download/itemdrops/itemdrops-v1.0.0.ipf

**Comment by xZeroW** [comment]
thank you
