### ISSUE TITLE
New addon request - simpler and small status bars

### ISSUE THREAD

**Issue by Ersakoz** [weizlogy/tos#14]
Is it possible to make Status Bar simplified?
meaning make HP/SP/Stamina and class as simple UI and smaller. 
![image](https://user-images.githubusercontent.com/34126339/34466673-3b2e1c94-ef17-11e7-85b3-038dbf0811d7.png)

something like this

**Comment by weizlogy** [comment]
compactheadsupdisplay.ipf makes hidden gauges on heads up display.
And then staminigauge makes add stamina gauge below character's gauges.

I'll make addon to add gauges text(hp/maxhp, and so on) on character's gauges.

How about this?

**Comment by Ersakoz** [comment]
Thank you weizlogy for the response! It sounds like a good idea to add it on 😄

**Comment by weizlogy** [comment]
![default](https://user-images.githubusercontent.com/26444581/34664944-afda77ec-f4a1-11e7-9a64-21f61892dfcf.PNG)

ξ╹-╹๑Ҙ

**Comment by Ersakoz** [comment]
Yes this is perfect!

Will this display be only for yourself or does it include others.

**Comment by weizlogy** [comment]
it's only myself.

**Comment by Ersakoz** [comment]
Sounds good, as it we be very neat!  ( Instead of showing others HP/SP/stamina too )

**Comment by weizlogy** [comment]
;)

[minigaugetext-v1.0.0.ipf](https://github.com/weizlogy/tos/releases/download/minigaugetext/minigaugetext-v1.0.0.ipf)

**Comment by Ersakoz** [comment]
Thanks !!!😁
