### ISSUE TITLE
Bug Pick-Item Info on 21:9 Aspect Ratio resolution

### ISSUE THREAD

**Issue by Questionguy663** [weizlogy/tos#15]
I think the bug is the game being at 3440x1440 resolution anyway, when any item drops the name is always the exact same distance offset (up and left) like in this picture, If you need me to take any more pictures or video or test a new version to see if it works I can do that! :)

![20180114155249_2](https://user-images.githubusercontent.com/19497435/34918395-f6f2a09e-f949-11e7-89c9-7aacca01d407.jpg)

**Comment by weizlogy** [comment]
hmm...
latest version do you use?

**Comment by Questionguy663** [comment]
Version 1.0.3
![weizfixingpickiteminfo1](https://user-images.githubusercontent.com/19497435/35085583-39bea024-fc21-11e7-8887-d0f0ffa1c890.jpg)

I took some more pictures

![20180114155249_1](https://user-images.githubusercontent.com/19497435/35085672-a2350ac6-fc21-11e7-8e63-49aeb7564e39.jpg)

![20180115102622_1](https://user-images.githubusercontent.com/19497435/35085678-a82836a6-fc21-11e7-9d8b-9206931ffbfc.jpg)

![20180116093149_1](https://user-images.githubusercontent.com/19497435/35085684-adc681d0-fc21-11e7-81dd-32db98693f68.jpg)

I drew some arrows on these last two because they get a bit confusing

![weizfixingpickiteminfo99](https://user-images.githubusercontent.com/19497435/35085817-2cc7700c-fc22-11e7-808c-a4accea47b47.jpg)

![weizfixingpickiteminfo100](https://user-images.githubusercontent.com/19497435/35085821-304cf7b0-fc22-11e7-9819-e668509b8af2.jpg)

I'm ready to try anything! Removing other Addons, trying other resolutions, testing a new version or  editing some different values, you name it I'll try it.

![emoticon_0006](https://user-images.githubusercontent.com/19497435/35085883-65c92bd4-fc22-11e7-8c3b-5db6620179ff.png)

**Comment by weizlogy** [comment]
Thanks for captureing.

Then, display drop item name by default action (ALT-key pressed) that works correctly?

**Comment by Questionguy663** [comment]
Here is the ALT key pressed picture. Looks quite normal.

![20180118190104_1](https://user-images.githubusercontent.com/19497435/35116066-0b260ea8-fc82-11e7-8c9c-995483584251.jpg)

**Comment by weizlogy** [comment]
Looks quite normal...

Can you try this one?
[pickiteminfo.zip](https://github.com/weizlogy/tos/files/1646558/pickiteminfo.zip)

**Comment by Questionguy663** [comment]
I tried the new version (added a _ to the name)


![20180119133644_1](https://user-images.githubusercontent.com/19497435/35153425-62ffe256-fd1e-11e7-9e12-22fcd8ca2b58.jpg)

The result didn't change yet

![20180119133643_1](https://user-images.githubusercontent.com/19497435/35153441-708de58a-fd1e-11e7-9cc4-b71fdb827c99.jpg)

**Comment by weizlogy** [comment]
hmm...how about item drops addon.

https://github.com/weizlogy/tos/releases/download/itemdrops/itemdrops-v1.0.0.ipf

**Comment by Questionguy663** [comment]
added _ and 📖 to file name

Item drops has two bugs, I have to run off of the screen and back to the item before a name appears, and then the name is also a little way away from the item, here is a quick video I uploaded.

https://youtu.be/exJ3ZePimJI

**Comment by weizlogy** [comment]
Fix axis!!

[📖pickiteminfo.zip](https://github.com/weizlogy/tos/files/1649050/pickiteminfo.zip)

**Comment by Questionguy663** [comment]
I like the change where you can see the full name of the item drops now a item called: 

"Two Handed Dratt Sword" was 
"Two Handed Dr....."

But the issue didn't change. I figured out what the problem was though! It's IMC's bug with the game!

I just realised the monster spells are off too:

![20180121163901_1](https://user-images.githubusercontent.com/19497435/35216466-9d450f3e-ff5f-11e7-9ada-cb912a4edee1.jpg)![20180121165912_1](https://user-images.githubusercontent.com/19497435/35216537-df12c410-ff5f-11e7-8123-d2501be67f2a.jpg)

And the map is off but I've known about this for a while and forgot to mention it.

![20180119145608_2](https://user-images.githubusercontent.com/19497435/35216707-6cae4ff6-ff60-11e7-9822-c37eb0110b69.jpg)

So it's all IMC's bug. Issue solved! The problem will be getting IMC to fix it, I don't think the English version makes them much money.
![emoticon_0016](https://user-images.githubusercontent.com/19497435/35216749-977e6aae-ff60-11e7-98b5-941c03fa661f.PNG)

Sorry for wasting your time, but thank you again for fixing long item names.

**Comment by Questionguy663** [comment]
https://forum.treeofsavior.com/t/21-9-aspect-ratio-tons-of-overlay-elements-still-completely-off-axis/376936 I now have a Forum thread for Bug Fix on the official forum, it's up to IMC now.



![emoticon_0002](https://user-images.githubusercontent.com/19497435/35351073-bb78e7e4-0137-11e8-8b5a-d81f5f80251a.png)
