### ISSUE TITLE
cannot install pick-item info on mizuki jtos addon manager version

### ISSUE THREAD

**Issue by maitokr2** [weizlogy/tos#16]
![captura de tela 2018-01-25 12 28 33](https://user-images.githubusercontent.com/34316474/35393134-44632d6a-01cb-11e8-9049-902cc3a9d987.png)

**Comment by weizlogy** [comment]
Could you try install this addon directly?

[http://www.weizlogy.gq/tos/addon/pickiteminfo/](http://www.weizlogy.gq/tos/addon/pickiteminfo/)

**Comment by maitokr2** [comment]
Directly works fine, even on version 1.0.3 but I don't know why addon manager did this.
I'll try this version.
