### ISSUE TITLE
Summoncounter no icons International Tree of Savior

### ISSUE THREAD

**Issue by Questionguy663** [weizlogy/tos#23]
I can't seem to get Summon Counter to show the icon's on the screen, I made the settings.txt and entered the information but nothing seems to happen.

I have Objectdetector working and you need to make a settings.txt for that one too, but could you check I did this right?

![20170221002915_1](https://user-images.githubusercontent.com/19497435/41411663-7d8a67e8-6fd5-11e8-816b-6b887d1775a7.jpg)

**Comment by weizlogy** [comment]
It seems to right.
This text file's encoding need to UTF8(No BOM

**Comment by Questionguy663** [comment]
I have a screenshot of the working settings.txt of object detector and in game screenshot, do you think it's a problem with the spacing on the lines? the blank space at the beggining of the lines is a lot shorter on Objectdetector.

![xxxxxxxxxxxxxxxxxxxxxxxxxx](https://user-images.githubusercontent.com/19497435/41509731-4f7a3112-7250-11e8-87b1-68b26d4d85eb.jpg)

![zzzzzzzzzzzzzzzzzzzzz](https://user-images.githubusercontent.com/19497435/41509733-55df92d6-7250-11e8-8001-5d24094e5e1d.jpg)

**Comment by weizlogy** [comment]
After 6/27 JP Update, Reproduce the bug. Then fix it.
Please try new version.

-- sorry for late
