### ISSUE TITLE
[skill-item counter] incorrect number of uses

### ISSUE THREAD

**Issue by NoctisCepheus** [weizlogy/tos#37]
i have 500 magic rounds. on cast of enchanters "reinforce" skill uses 2 magic rounds. the counter should display 250 uses, right? it instead displays 125. happens on most other skills as well.

**Comment by weizlogy** [comment]
It is ReBuild problems. But ReBuild is not coming yet in JToS. (Then I cant fixed.
It seems there are people who corresponded with Discord so please use it for a while.

https://cdn.discordapp.com/attachments/343598546941116417/539463042380070912/skillitemcounter--rebuild.ipf

**Comment by weizlogy** [comment]
リビルドが日本に来たのでそろそろ対応をしていきます。
