### ISSUE TITLE
DPS Meter

### ISSUE THREAD

**Issue by Abeson** [weizlogy/tos#38]
Hello, you also intends to update the DPS Meter? It does not currently work and I'd like to have some way to see the damage done in combos.
Thanks for the effort!

**Comment by weizlogy** [comment]
I thought no one was using it, and I am thinking of updating later.

**Comment by weizlogy** [comment]
Hi, I just finished to fixing dpsmeter and released as v2.0.0 in AddonManager.

**Comment by Abeson** [comment]
Thanks a lot! You are amazing :D
